---
driver:
  provision: true

provisioner:
  name: puppet_apply
  manifests_path: manifests
  manifest: local.pp
  modules_path: modules
  hiera_data_path: data
  hiera_deep_merge: false
  puppet_verbose: true
  puppet_debug: false
  require_chef_for_busser: false
  require_puppet_repo: false
  custom_options: '--show_diff'
  verify_host_key: false
  hiera_config_path: "hiera-testing.yaml"

transport:
  name: sftp

busser:
  ruby_bindir: /usr/bin

platforms:
  - name: ubuntu16-hosting_basesetup
    driver_plugin: vagrant
    driver:
      vagrantfile_erb: vagrantfiles/Vagrantfile-debianoid.erb
      box: ubuntu/xenial64
      box_url: https://app.vagrantup.com/ubuntu/boxes/xenial64
      synced_folders:
        - ['./files', '/tmp/files']
      #network:
      #- ['private_network', {ip: '192.168.33.33'}]
      #- ["forwarded_port", {guest: 8080, host: 8080}]
  - name: ubuntu18-hosting_basesetup
    driver_plugin: vagrant
    driver:
      vagrantfile_erb: vagrantfiles/Vagrantfile-debianoid.erb
      box: ubuntu/bionic64
      box_url: https://app.vagrantup.com/ubuntu/boxes/bionic64
      synced_folders:
        - ['./files', '/tmp/files']
      #network:
      #- ['private_network', {ip: '192.168.33.33'}]
      #- ["forwarded_port", {guest: 8080, host: 8080}]
  - name: ubuntu20-hosting_basesetup
    driver_plugin: vagrant
    driver:
      vagrantfile_erb: vagrantfiles/Vagrantfile-debianoid.erb
      box: ubuntu/focal64
      box_url: https://app.vagrantup.com/ubuntu/boxes/focal64
      synced_folders:
        - ['./files', '/tmp/files']
      #network:
      #- ['private_network', {ip: '192.168.33.33'}]
      #- ["forwarded_port", {guest: 8080, host: 8080}]
  - name: ubuntu22-hosting_basesetup
    driver_plugin: vagrant
    driver:
      vagrantfile_erb: vagrantfiles/Vagrantfile-debianoid.erb
      box: ubuntu/jammy64
      box_url: https://app.vagrantup.com/ubuntu/boxes/jammy64
      synced_folders:
        - ['./files', '/tmp/files']
      #network:
      #- ['private_network', {ip: '192.168.33.33'}]
      #- ["forwarded_port", {guest: 8080, host: 8080}]
      #transport: # Dealing with 22.04 deprecating ssh-rsa prior to tooling being ready for it
      #name: ssh
      #username: vagrant
      #password: vagrant

  - name: debian-hosting_basesetup
    driver_plugin: vagrant
    driver:
      vagrantfile_erb: vagrantfiles/Vagrantfile-debianoid.erb
      box: debian/contrib-stretch64
      box_url: https://app.vagrantup.com/debian/boxes/contrib-stretch64
      #network:
      #- ['private_network', {ip: '192.168.33.34'}]
      #- ["forwarded_port", {guest: 8080, host: 8080}]
      #
  - name: centos7-hosting_basesetup
    driver_plugin: vagrant
    driver:
      vagrantfile_erb: vagrantfiles/Vagrantfile-centos.erb
      box: centos/7
      box_url: https://app.vagrantup.com/centos/boxes/7
suites:
  - name: default

