#!/bin/bash

FILE="/var/log/meminfo"
FILE_LIMIT=$((10*1024*1024))

if [ -f "$FILE" ]; then
    FILESIZE=$(wc -c "$FILE" | awk '{print $1}')
    if [ $FILESIZE -ge $FILE_LIMIT ]; then
        cp $FILE $FILE.1
        : > $FILE
    fi
fi

echo "\n\n------------------------------" >> $FILE
date +"%m-%d-%Y %H:%M:%S" >> $FILE
echo "------------------------------" >> $FILE
ps -eo pmem,pcpu,vsize,pid,cmd | sort -k 1 -nr | head -10 >> $FILE
echo "------------------------------\n" >> $FILE
