#!/bin/bash


if [ "$(whoami)" != "root" ];then
  echo "INFO: not root, executing myself with sudo"
  exec sudo $0
fi
unset LC_ALL
unset LANG

if ( [ "$(lsb_release --id --short)" == "Ubuntu" ] || [ "$(lsb_release --id --short)" == "Debian" ] );then
   set -x
   set -e
   puppet agent --disable "System update in progress"
   apt autoremove -y
   apt update 
   apt upgrade -y
   apt dist-upgrade -y
   puppet agent --enable
   set +x 
else 
   echo "ERROR: not implemented"
   exit 1
fi
